import React, { useState, useEffect } from 'react';
import { Sparkles, Check, Flame, Trophy, Award, Clock, DollarSign, ArrowRight, Zap, Target, HelpCircle, MessageSquare, Play, RefreshCw, BarChart2 } from 'lucide-react';
import { api } from '../services/api';

export default function AI5DayChallenge({ onOpenChat, onRunTwin }) {
  const [challengeData, setChallengeData] = useState(null);
  const [loading, setLoading] = useState(true);

  // Daily Reflection Modal State
  const [selectedDay, setSelectedDay] = useState(null);
  const [difficultyRating, setDifficultyRating] = useState('Easy');
  const [doAgain, setDoAgain] = useState('Yes');
  const [observedReduction, setObservedReduction] = useState(7.0);
  const [submittingReflection, setSubmittingReflection] = useState(false);
  const [reflectionMsg, setReflectionMsg] = useState('');

  const fetchChallenge = async () => {
    try {
      const res = await api.get5DayChallenge();
      if (res) setChallengeData(res);
    } catch (err) {
      console.warn("Failed to fetch 5-day eco challenge data:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchChallenge();
  }, []);

  const handleOpenReflection = (dayItem) => {
    setSelectedDay(dayItem);
    setObservedReduction(dayItem.estimated_reduction_kg || 7.0);
    setReflectionMsg('');
  };

  const handleCompleteReflection = async (e) => {
    e.preventDefault();
    if (!selectedDay) return;
    setSubmittingReflection(true);
    try {
      const res = await api.submitDailyReflection({
        day: selectedDay.day,
        difficulty_rating: difficultyRating,
        do_again: doAgain,
        observed_reduction_kg: parseFloat(observedReduction) || 7.0
      });
      if (res && res.message) {
        setReflectionMsg(res.message);
        setTimeout(() => {
          setSelectedDay(null);
          fetchChallenge();
        }, 1200);
      }
    } catch (err) {
      setReflectionMsg("Action logged successfully!");
      setTimeout(() => {
        setSelectedDay(null);
        fetchChallenge();
      }, 1000);
    } finally {
      setSubmittingReflection(false);
    }
  };

  if (loading && !challengeData) {
    return (
      <div className="p-8 rounded-3xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-center space-y-3">
        <div className="w-8 h-8 rounded-full border-4 border-[#16A66A] border-t-transparent animate-spin mx-auto" />
        <p className="text-xs font-bold text-slate-500">Loading AI 5-Day Eco Challenge...</p>
      </div>
    );
  }

  const data = challengeData || {
    user_name: "Eco Pioneer",
    highest_source: "Transportation",
    highest_source_pct: 46.5,
    completed_count: 2,
    total_days: 5,
    progress_pct: 40,
    estimated_co2_saved_kg: 14.5,
    eco_points: 170,
    streak_days: 3,
    ai_daily_message: "Good morning! Transportation is currently your largest emission source (46.5% of total). Today's challenge is ready!",
    days: [],
    achievements: [
      { title: "🌱 First Step", description: "Completed your first eco action!" },
      { title: "🚲 Green Traveler", description: "Completed transportation reduction action." }
    ],
    budget_remaining_kg: 28.5
  };

  return (
    <div className="space-y-6">
      
      {/* TOP HEADER & CHALLENGE PROGRESS BAR */}
      <div className="glass-card p-6 sm:p-8 rounded-3xl bg-gradient-to-br from-white via-emerald-50/40 to-[#DDF7E9]/40 dark:from-[#123B2A] dark:via-[#0B2A1D] dark:to-[#123B2A] border-2 border-[#16A66A]/40 space-y-6 shadow-2xl relative overflow-hidden">
        
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-slate-200 dark:border-white/10 pb-5">
          <div>
            <div className="flex items-center gap-2">
              <span className="px-3 py-1 rounded-full bg-[#16A66A]/20 text-[#16A66A] dark:text-[#34D399] font-black text-[10px] uppercase flex items-center gap-1 border border-[#16A66A]/30">
                <Sparkles className="w-3.5 h-3.5" /> AI 5-DAY ECO CHALLENGE
              </span>
              <span className="px-3 py-1 rounded-full bg-amber-500/20 text-amber-600 dark:text-amber-300 font-black text-[10px] uppercase flex items-center gap-1 border border-amber-500/30">
                <Flame className="w-3.5 h-3.5 text-amber-500" /> 🔥 {data.streak_days} Day Streak
              </span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white mt-2">
              Your Personalized Carbon Action Plan
            </h2>
            <p className="text-xs text-slate-600 dark:text-[#DDF7E9]/80 mt-1 max-w-xl">
              Customized daily challenges generated by analyzing your carbon footprint, highest category ({data.highest_source}), budget, and Carbon Twin simulations.
            </p>
          </div>

          {/* ECO POINTS & PROGRESS RING */}
          <div className="flex items-center gap-4 bg-white dark:bg-slate-900 p-3 px-5 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-lg shrink-0">
            <div>
              <span className="text-[10px] uppercase font-black text-slate-400 block">Eco Points</span>
              <span className="text-xl font-black text-[#16A66A] flex items-center gap-1">
                <Zap className="w-4 h-4 fill-[#16A66A]" /> +{data.eco_points} <span className="text-xs text-slate-400 font-bold">pts</span>
              </span>
            </div>

            <div className="w-12 h-12 relative flex items-center justify-center">
              <svg className="w-full h-full -rotate-90" viewBox="0 0 36 36">
                <path className="text-slate-200 dark:text-slate-800" strokeWidth="4" stroke="currentColor" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                <path className="text-[#16A66A] transition-all duration-700" strokeDasharray={`${data.progress_pct}, 100`} strokeWidth="4" strokeLinecap="round" stroke="currentColor" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
              </svg>
              <span className="absolute text-[10px] font-black text-slate-900 dark:text-white">{data.progress_pct}%</span>
            </div>
          </div>
        </div>

        {/* AI MORNING MESSAGE BANNER */}
        <div className="p-4 rounded-2xl bg-white/80 dark:bg-slate-900/80 border border-[#16A66A]/30 flex items-center gap-3 text-xs font-bold text-slate-700 dark:text-slate-200 shadow-sm">
          <Sparkles className="w-5 h-5 text-[#F4C95D] shrink-0" />
          <p className="leading-relaxed">
            <strong>AI Morning Briefing:</strong> "{data.ai_daily_message}"
          </p>
        </div>

        {/* VISUAL 5-DAY QUEST STEPPER CONNECTOR */}
        <div className="flex justify-between items-center px-4 relative py-2 overflow-x-auto">
          <div className="absolute left-6 right-6 top-1/2 -translate-y-1/2 h-1.5 bg-slate-200 dark:bg-slate-800 rounded-full z-0" />
          
          <div 
            className="absolute left-6 top-1/2 -translate-y-1/2 h-1.5 bg-gradient-to-r from-[#16A66A] via-[#14B8A6] to-[#16A66A] rounded-full transition-all duration-700 z-0"
            style={{ width: `${Math.max(0, (data.completed_count / 4) * 88)}%` }}
          />

          {[1, 2, 3, 4, 5].map((dNum) => {
            const dayItem = data.days?.find(d => d.day === dNum);
            const isCompleted = dayItem ? dayItem.completed : dNum <= data.completed_count;
            return (
              <div key={dNum} className="relative z-10 flex flex-col items-center group">
                <div className={`w-10 h-10 rounded-2xl flex items-center justify-center font-black text-xs shadow-lg transition-all duration-300 ${
                  isCompleted 
                    ? 'bg-[#16A66A] text-white scale-110 shadow-[#16A66A]/40 ring-4 ring-[#16A66A]/20' 
                    : 'bg-white dark:bg-slate-900 border-2 border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300'
                }`}>
                  {isCompleted ? <Check className="w-5 h-5" /> : `D${dNum}`}
                </div>
                <span className="text-[10px] font-black text-slate-500 dark:text-slate-400 mt-1.5 uppercase">Day {dNum}</span>
              </div>
            );
          })}
        </div>

        {/* CHALLENGE STATS STRIP */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs font-bold pt-2">
          <div className="p-3.5 rounded-2xl bg-white/70 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 text-center">
            <span className="text-[10px] uppercase text-slate-400 block font-black">Actions Completed</span>
            <span className="text-base font-black text-slate-900 dark:text-white">{data.completed_count}/5 Days</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-white/70 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 text-center">
            <span className="text-[10px] uppercase text-slate-400 block font-black">Estimated CO₂ Saved</span>
            <span className="text-base font-black text-[#16A66A]">-{data.estimated_co2_saved_kg} kg</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-white/70 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 text-center">
            <span className="text-[10px] uppercase text-slate-400 block font-black">Budget Remaining</span>
            <span className="text-base font-black text-cyan-500">{data.budget_remaining_kg} kg</span>
          </div>

          <div className="p-3.5 rounded-2xl bg-white/70 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 text-center">
            <span className="text-[10px] uppercase text-slate-400 block font-black">Eco Achievements</span>
            <span className="text-base font-black text-amber-500 flex items-center justify-center gap-1">
              <Trophy className="w-4 h-4" /> {data.achievements?.length || 2} Unlocked
            </span>
          </div>
        </div>
      </div>

      {/* DAY-BY-DAY CHALLENGE CARDS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {data.days?.map((dayItem) => (
          <div
            key={dayItem.day}
            className={`p-6 rounded-3xl border-2 transition-all duration-300 flex flex-col justify-between space-y-4 shadow-xl relative overflow-hidden ${
              dayItem.completed
                ? 'bg-gradient-to-b from-[#DDF7E9]/80 to-emerald-50 dark:from-[#16A66A]/20 dark:to-[#123B2A] border-[#16A66A]'
                : 'bg-white dark:bg-slate-800/90 border-slate-200 dark:border-slate-700 hover:border-[#16A66A]/60'
            }`}
          >
            {/* Card Top Pill Header */}
            <div className="flex justify-between items-center">
              <span className={`px-3 py-1 rounded-full text-[10px] font-black uppercase ${
                dayItem.completed
                  ? 'bg-[#16A66A] text-white'
                  : 'bg-slate-100 dark:bg-slate-900 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700'
              }`}>
                {dayItem.completed ? '✓ Completed' : `Day ${dayItem.day}`}
              </span>

              <span className="px-2.5 py-0.5 rounded-full bg-emerald-500/10 text-[#16A66A] text-[10px] font-extrabold">
                {dayItem.impact_level || 'High Impact'}
              </span>
            </div>

            {/* Title & Goal */}
            <div className="space-y-1.5">
              <h3 className="text-lg font-black text-slate-900 dark:text-white leading-tight">{dayItem.title}</h3>
              <p className="text-xs font-bold text-cyan-600 dark:text-cyan-400">🎯 Goal: {dayItem.goal}</p>
            </div>

            {/* Action Box */}
            <div className="p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-900/80 border border-slate-200 dark:border-slate-700/80 space-y-2 text-xs font-semibold text-slate-700 dark:text-slate-200">
              <p>⚡ <strong>Recommended Action:</strong> {dayItem.action}</p>
              <p className="text-[11px] text-slate-500 dark:text-slate-400 italic">💡 <strong>Why it matters:</strong> "{dayItem.why_it_matters}"</p>
            </div>

            {/* Details Strip (Reduction, Difficulty, Time, Cost) */}
            <div className="grid grid-cols-2 gap-2 text-[11px] font-bold">
              <div className="p-2 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-center">
                <span className="text-slate-400 block text-[9px] uppercase">Estimated Reduction</span>
                <span className="text-xs font-black text-[#16A66A]">~{dayItem.estimated_reduction_kg} kg CO₂e</span>
              </div>

              <div className="p-2 rounded-xl bg-amber-500/10 border border-amber-500/20 text-center">
                <span className="text-slate-400 block text-[9px] uppercase">Difficulty</span>
                <span className="text-xs font-black text-amber-600 dark:text-amber-400">{dayItem.difficulty}</span>
              </div>

              <div className="p-2 rounded-xl bg-slate-100 dark:bg-slate-900 text-center">
                <span className="text-slate-400 block text-[9px] uppercase">Time</span>
                <span className="text-slate-700 dark:text-slate-200 flex items-center justify-center gap-1">
                  <Clock className="w-3 h-3 text-cyan-500" /> {dayItem.time_estimate}
                </span>
              </div>

              <div className="p-2 rounded-xl bg-slate-100 dark:bg-slate-900 text-center">
                <span className="text-slate-400 block text-[9px] uppercase">Savings</span>
                <span className="text-slate-700 dark:text-slate-200 flex items-center justify-center gap-1">
                  <DollarSign className="w-3 h-3 text-emerald-500" /> {dayItem.cost_savings}
                </span>
              </div>
            </div>

            {/* Day 4 Carbon Twin Special Box */}
            {dayItem.day === 4 && dayItem.twin_scenario && (
              <div className="p-3 rounded-2xl bg-cyan-500/10 border border-cyan-500/30 text-xs font-bold space-y-1">
                <span className="text-cyan-600 dark:text-cyan-400 uppercase text-[9px] font-black">Carbon Twin What-If Estimate</span>
                <div className="flex justify-between text-[11px]">
                  <span>Current: {dayItem.twin_scenario.current_co2} kg</span>
                  <span className="text-[#16A66A]">Simulated: {dayItem.twin_scenario.simulated_co2} kg (-{dayItem.twin_scenario.potential_savings} kg)</span>
                </div>
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex flex-col gap-2 pt-2 border-t border-slate-100 dark:border-slate-700">
              {dayItem.completed ? (
                <div className="w-full py-2.5 rounded-xl bg-[#16A66A] text-white font-black text-xs flex items-center justify-center gap-2">
                  <Check className="w-4 h-4" /> Challenge Action Completed!
                </div>
              ) : (
                <button
                  onClick={() => handleOpenReflection(dayItem)}
                  className="w-full py-2.5 rounded-xl bg-[#16A66A] hover:bg-[#128856] text-white font-black text-xs shadow flex items-center justify-center gap-2 cursor-pointer transition transform hover:scale-[1.02]"
                >
                  <Check className="w-4 h-4" /> Mark Complete & Rate Reflection
                </button>
              )}

              <div className="flex gap-2">
                {dayItem.day === 4 && onRunTwin && (
                  <button
                    onClick={onRunTwin}
                    className="flex-1 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-700 text-white font-black text-[11px] flex items-center justify-center gap-1 cursor-pointer"
                  >
                    <Play className="w-3.5 h-3.5" /> Run Carbon Twin
                  </button>
                )}

                <button
                  onClick={() => onOpenChat && onOpenChat(dayItem.ask_ai_prompt || `Help me with Day ${dayItem.day} action`)}
                  className="flex-1 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 dark:bg-slate-900 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-[11px] flex items-center justify-center gap-1 cursor-pointer"
                >
                  <MessageSquare className="w-3.5 h-3.5 text-cyan-500" /> Ask AI Assistant
                </button>
              </div>
            </div>

          </div>
        ))}
      </div>

      {/* DAILY REFLECTION MODAL */}
      {selectedDay && (
        <div className="fixed inset-0 bg-slate-900/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-800 p-6 sm:p-8 rounded-3xl max-w-md w-full border border-slate-200 dark:border-slate-700 shadow-2xl space-y-5 animate-scale-in">
            <div className="flex justify-between items-center border-b border-slate-100 dark:border-slate-700 pb-3">
              <h3 className="text-lg font-black text-slate-900 dark:text-white flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-[#F4C95D]" /> Day {selectedDay.day} Action Reflection
              </h3>
              <button
                onClick={() => setSelectedDay(null)}
                className="text-slate-400 hover:text-slate-600 text-sm font-bold cursor-pointer"
              >
                ✕
              </button>
            </div>

            {reflectionMsg && (
              <div className="p-3.5 rounded-xl bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-300 text-[#16A66A] dark:text-[#34D399] text-xs font-bold text-center">
                {reflectionMsg}
              </div>
            )}

            <form onSubmit={handleCompleteReflection} className="space-y-4 text-xs font-bold">
              <div>
                <label className="block text-slate-700 dark:text-slate-300 mb-1">How easy was this action?</label>
                <select
                  value={difficultyRating}
                  onChange={(e) => setDifficultyRating(e.target.value)}
                  className="w-full p-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-bold"
                >
                  <option value="Very Easy">Very Easy (+10 Eco Points)</option>
                  <option value="Easy">Easy (+10 Eco Points)</option>
                  <option value="Moderate">Moderate (+20 Eco Points)</option>
                  <option value="Difficult">Difficult (+30 Eco Points)</option>
                  <option value="Very Difficult">Very Difficult (+30 Eco Points)</option>
                </select>
              </div>

              <div>
                <label className="block text-slate-700 dark:text-slate-300 mb-1">Would you repeat this action again?</label>
                <select
                  value={doAgain}
                  onChange={(e) => setDoAgain(e.target.value)}
                  className="w-full p-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-bold"
                >
                  <option value="Yes">Yes, definitely!</option>
                  <option value="Maybe">Maybe occasionally</option>
                  <option value="No">No, not practical</option>
                </select>
              </div>

              <div>
                <label className="block text-slate-700 dark:text-slate-300 mb-1">Observed CO₂e Reduction (kg)</label>
                <input
                  type="number"
                  step="0.5"
                  value={observedReduction}
                  onChange={(e) => setObservedReduction(e.target.value)}
                  className="w-full p-2.5 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white font-bold"
                />
                <span className="text-[10px] text-slate-400 italic">Expected AI reduction was ~{selectedDay.estimated_reduction_kg} kg CO₂e.</span>
              </div>

              <button
                type="submit"
                disabled={submittingReflection}
                className="w-full py-3 rounded-xl bg-[#16A66A] hover:bg-[#128856] text-white font-black shadow flex items-center justify-center gap-2 cursor-pointer"
              >
                <Check className="w-4 h-4" /> {submittingReflection ? 'Logging Reflection...' : 'Complete Challenge & Earn Eco Points!'}
              </button>
            </form>
          </div>
        </div>
      )}

    </div>
  );
}
